-- Watchlist Supabase/Postgres schema.
-- Run this in Supabase SQL Editor before importing data from watchlist.db.
-- The app currently keeps its own users table and custom JWT auth; do not expose
-- these tables directly to the frontend with anon keys.

create extension if not exists citext;

create table if not exists public.users (
  id integer generated by default as identity primary key,
  name citext not null,
  email citext not null,
  password text not null,
  role text not null default 'user',
  account_status text not null default 'active',
  presence_status text not null default 'online',
  last_seen timestamptz,
  online_visibility text not null default 'everyone',
  profile_visibility text not null default 'everyone',
  friend_request_policy text not null default 'everyone',
  preferred_language text not null default 'UK',
  avatar_url text not null default '',
  cover_url text not null default '',
  bio text not null default '',
  favorite_genres text not null default '[]',
  constraint users_role_check check (role in ('user', 'admin')),
  constraint users_account_status_check check (account_status in ('active', 'blocked')),
  constraint users_presence_status_check check (presence_status in ('online', 'offline', 'dnd', 'hidden')),
  constraint users_online_visibility_check check (online_visibility in ('everyone', 'friends', 'nobody')),
  constraint users_profile_visibility_check check (profile_visibility in ('everyone', 'friends', 'nobody')),
  constraint users_friend_request_policy_check check (friend_request_policy in ('everyone', 'friends', 'nobody')),
  constraint users_preferred_language_check check (preferred_language in ('UK', 'RU', 'EN'))
);

create unique index if not exists idx_users_name_unique on public.users (lower(name::text));
create unique index if not exists idx_users_email_unique on public.users (lower(email::text));

create table if not exists public.entries (
  id integer generated by default as identity primary key,
  user_id integer references public.users(id) on delete cascade,
  title text not null,
  type text not null default 'movie',
  status text not null default 'completed',
  rating integer default 0,
  year integer,
  genre text,
  tags text,
  mood text default '',
  poster_url text default '',
  director text default '',
  runtime integer default 0,
  comment text default '',
  current_season integer default 0,
  current_episode integer default 0,
  next_episode_date text default '',
  created_by_admin boolean not null default false,
  sort_order integer not null default 0,
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  constraint entries_rating_check check (rating between 0 and 5),
  constraint entries_type_check check (type in ('movie', 'series', 'game'))
);

create unique index if not exists idx_entries_unique
  on public.entries (user_id, lower(title), type, coalesce(year, 0));
create index if not exists idx_entries_user_sort on public.entries (user_id, sort_order, created_at desc);
create index if not exists idx_entries_public on public.entries (created_by_admin) where created_by_admin = true;

create table if not exists public.friends (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  friend_id integer not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  requested_by integer not null references public.users(id) on delete cascade,
  interactions integer not null default 0,
  messages_count integer not null default 0,
  games_count integer not null default 0,
  streak_days integer not null default 0,
  last_interaction_at timestamptz,
  muted_by_user boolean not null default false,
  muted_by_friend boolean not null default false,
  blocked_by_user boolean not null default false,
  blocked_by_friend boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, friend_id),
  constraint friends_status_check check (status in ('pending', 'accepted', 'rejected', 'cancelled', 'blocked'))
);

create index if not exists idx_friends_pair on public.friends (user_id, friend_id, status);
create index if not exists idx_friends_requested_by on public.friends (requested_by, status);

create table if not exists public.friend_messages (
  id integer generated by default as identity primary key,
  relation_id integer not null references public.friends(id) on delete cascade,
  sender_id integer not null references public.users(id) on delete cascade,
  receiver_id integer not null references public.users(id) on delete cascade,
  body text not null,
  content_title text not null default '',
  content_url text not null default '',
  content_meta text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_friend_messages_relation on public.friend_messages (relation_id, created_at);
create index if not exists idx_friend_messages_receiver_unread
  on public.friend_messages (receiver_id, read_at)
  where read_at is null;

create table if not exists public.teams (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null default '',
  owner_id integer not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id integer generated by default as identity primary key,
  team_id integer not null references public.teams(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  unique(team_id, user_id),
  constraint team_members_role_check check (role in ('admin', 'member'))
);

create index if not exists idx_team_members_user on public.team_members (user_id, team_id);

create table if not exists public.team_items (
  id integer generated by default as identity primary key,
  team_id integer not null references public.teams(id) on delete cascade,
  title text not null,
  type text not null default 'movie',
  status text not null default 'planned',
  scheduled_at timestamptz,
  created_by integer not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_team_items_team on public.team_items (team_id, created_at);

create table if not exists public.team_votes (
  id integer generated by default as identity primary key,
  item_id integer not null references public.team_items(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  value integer not null default 1,
  created_at timestamptz not null default now(),
  unique(item_id, user_id)
);

create table if not exists public.reports (
  id integer generated by default as identity primary key,
  user_id integer references public.users(id) on delete set null,
  email text not null default '',
  subject text not null,
  body text not null,
  status text not null default 'new',
  admin_response text not null default '',
  responded_at timestamptz,
  responded_by integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint reports_status_check check (status in ('new', 'reviewing', 'answered', 'closed'))
);

create index if not exists idx_reports_user_status on public.reports (user_id, status, created_at desc);

create table if not exists public.report_messages (
  id integer generated by default as identity primary key,
  report_id integer not null references public.reports(id) on delete cascade,
  sender_id integer references public.users(id) on delete set null,
  sender_role text not null default 'user',
  body text not null,
  created_at timestamptz not null default now(),
  constraint report_messages_sender_role_check check (sender_role in ('user', 'admin'))
);

create index if not exists idx_report_messages_report on public.report_messages (report_id, created_at);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  user_id integer references public.users(id) on delete set null,
  action text not null,
  details text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created on public.audit_logs (created_at);

create table if not exists public.registration_attempts (
  id integer generated by default as identity primary key,
  ip_hash text not null,
  email_domain text default '',
  result text not null default 'allowed',
  created_at timestamptz not null default now()
);

create index if not exists idx_registration_attempts_ip_created
  on public.registration_attempts (ip_hash, created_at);

-- Keep direct frontend Supabase API closed for now. The Express backend remains
-- the access layer and uses its own JWT/role checks.
alter table public.users enable row level security;
alter table public.entries enable row level security;
alter table public.friends enable row level security;
alter table public.friend_messages enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_items enable row level security;
alter table public.team_votes enable row level security;
alter table public.reports enable row level security;
alter table public.report_messages enable row level security;
alter table public.audit_logs enable row level security;
alter table public.registration_attempts enable row level security;

create or replace function public.sync_watchlist_identity_sequences()
returns void
language plpgsql
as $$
declare
  table_name text;
  sequence_name text;
  max_id bigint;
begin
  foreach table_name in array array[
    'users',
    'entries',
    'friends',
    'friend_messages',
    'teams',
    'team_members',
    'team_items',
    'team_votes',
    'reports',
    'report_messages',
    'audit_logs',
    'registration_attempts'
  ]
  loop
    sequence_name := pg_get_serial_sequence(format('public.%I', table_name), 'id');
    if sequence_name is not null then
      execute format('select coalesce(max(id), 0) from public.%I', table_name) into max_id;
      execute format('select setval(%L, greatest(%s, 1), true)', sequence_name, max_id);
    end if;
  end loop;
end;
$$;
