const { merge } = require('webpack-merge');
const common = require('./webpack.common.js');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = merge(common, {
  mode: 'production',
  plugins: [
    new HtmlWebpackPlugin({
      template: './index.html',
      inject: false,
    }),
    new CopyPlugin({
      patterns: [
        { from: 'css', to: 'css' },
        { from: 'js/auth.js', to: 'js/auth.js' },
        { from: 'js/admin.js', to: 'js/admin.js' },
        { from: 'js/friends.js', to: 'js/friends.js' },
        { from: 'js/home.js', to: 'js/home.js' },
        { from: 'js/marketing.js', to: 'js/marketing.js' },
        { from: 'js/messages.js', to: 'js/messages.js' },
        { from: 'js/profile.js', to: 'js/profile.js' },
        { from: 'js/settings.js', to: 'js/settings.js' },
        { from: 'js/teams.js', to: 'js/teams.js' },
        { from: 'icon.svg', to: 'icon.svg' },
        { from: 'favicon.ico', to: 'favicon.ico' },
        { from: 'robots.txt', to: 'robots.txt' },
        { from: 'icon.png', to: 'icon.png' },
        { from: 'icon-512.png', to: 'icon-512.png' },
        { from: 'sw.js', to: 'sw.js' },
        { from: '404.html', to: '404.html' },
        { from: 'about.html', to: 'about.html' },
        { from: 'admin.html', to: 'admin.html' },
        { from: 'api-docs.html', to: 'api-docs.html' },
        { from: 'catalog.html', to: 'catalog.html' },
        { from: 'changelog.html', to: 'changelog.html' },
        { from: 'community.html', to: 'community.html' },
        { from: 'contact-support.html', to: 'contact-support.html' },
        { from: 'discover.html', to: 'discover.html' },
        { from: 'friends.html', to: 'friends.html' },
        { from: 'help-center.html', to: 'help-center.html' },
        { from: 'integration-notes.html', to: 'integration-notes.html' },
        { from: 'legal.html', to: 'legal.html' },
        { from: 'login.html', to: 'login.html' },
        { from: 'messages.html', to: 'messages.html' },
        { from: 'partners.html', to: 'partners.html' },
        { from: 'privacy.html', to: 'privacy.html' },
        { from: 'products.html', to: 'products.html' },
        { from: 'profile.html', to: 'profile.html' },
        { from: 'register.html', to: 'register.html' },
        { from: 'roadmap.html', to: 'roadmap.html' },
        { from: 'security.html', to: 'security.html' },
        { from: 'settings.html', to: 'settings.html' },
        { from: 'scenarios/analytics.html', to: 'scenarios/analytics.html' },
        { from: 'scenarios/personal.html', to: 'scenarios/personal.html' },
        { from: 'scenarios/private-profile.html', to: 'scenarios/private-profile.html' },
        { from: 'scenarios/team-planning.html', to: 'scenarios/team-planning.html' },
        { from: 'scenarios/watch-with-friends.html', to: 'scenarios/watch-with-friends.html' },
        { from: 'teams.html', to: 'teams.html' },
        { from: 'terms.html', to: 'terms.html' },
        { from: 'use-cases.html', to: 'use-cases.html' },
        { from: 'watchlist.html', to: 'watchlist.html' },
        { from: 'watchlist-plus.html', to: 'watchlist-plus.html' },
        { from: 'site.webmanifest', to: 'site.webmanifest' },
      ],
    }),
  ],
});
