alter table public.users
  add column if not exists watchlist_plus_lifetime boolean not null default false,
  add column if not exists watchlist_plus_until timestamptz,
  add column if not exists watchlist_plus_granted_at timestamptz,
  add column if not exists watchlist_plus_granted_by integer;

create table if not exists public.user_watchlist_items (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  entry_id integer not null references public.entries(id) on delete cascade,
  status public."EntryStatus" not null default 'planned',
  current_season integer not null default 0,
  current_episode integer not null default 0,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_watchlist_items_user_entry_key unique (user_id, entry_id)
);

create index if not exists user_watchlist_items_user_status_updated_idx
  on public.user_watchlist_items(user_id, status, updated_at);
create index if not exists user_watchlist_items_entry_idx
  on public.user_watchlist_items(entry_id);

create or replace function private.watchlist_has_plus()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where auth_user_id = auth.uid()
      and account_status = 'active'
      and (
        role = 'admin'
        or watchlist_plus_lifetime = true
        or (watchlist_plus_until is not null and watchlist_plus_until > now())
      )
  )
$$;

alter table public.user_watchlist_items enable row level security;

drop policy if exists user_watchlist_items_owner_or_admin_select on public.user_watchlist_items;
create policy user_watchlist_items_owner_or_admin_select
on public.user_watchlist_items
for select
to authenticated
using (
  private.watchlist_is_admin()
  or (
    private.watchlist_has_plus()
    and user_id = private.watchlist_user_id()
  )
);

drop policy if exists user_watchlist_items_owner_or_admin_write on public.user_watchlist_items;
create policy user_watchlist_items_owner_or_admin_write
on public.user_watchlist_items
for all
to authenticated
using (
  private.watchlist_is_admin()
  or (
    private.watchlist_has_plus()
    and user_id = private.watchlist_user_id()
  )
)
with check (
  private.watchlist_is_admin()
  or (
    private.watchlist_has_plus()
    and user_id = private.watchlist_user_id()
  )
);
