create table if not exists public.mfa_reset_codes (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists mfa_reset_codes_user_id_expires_at_idx
  on public.mfa_reset_codes(user_id, expires_at);
