create table if not exists public.registration_attempts (
  id integer generated by default as identity primary key,
  ip_hash text not null,
  email_domain text not null default '',
  result text not null default 'allowed',
  created_at timestamptz not null default current_timestamp
);

create index if not exists idx_registration_attempts_ip_created
  on public.registration_attempts (ip_hash, created_at);
