alter table public.users
  add column if not exists auth_user_id uuid unique;

create table if not exists public.report_attachments (
  id integer generated by default as identity primary key,
  report_id integer not null references public.reports(id) on delete cascade,
  report_message_id integer references public.report_messages(id) on delete set null,
  user_id integer references public.users(id) on delete set null,
  file_name text not null,
  file_type text not null,
  file_size integer not null,
  storage_path text not null,
  public_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists report_attachments_report_created_idx on public.report_attachments(report_id, created_at);
create index if not exists report_attachments_user_idx on public.report_attachments(user_id);

create schema if not exists private;
revoke all on schema private from anon, authenticated;

create or replace function private.watchlist_user_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where auth_user_id = auth.uid() limit 1
$$;

create or replace function private.watchlist_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where auth_user_id = auth.uid()
      and role = 'admin'
      and account_status = 'active'
  )
$$;

alter table public.users enable row level security;
alter table public.entries enable row level security;
alter table public.entry_reactions enable row level security;
alter table public.friends enable row level security;
alter table public.friend_messages enable row level security;
alter table public.reports enable row level security;
alter table public.report_messages enable row level security;
alter table public.report_attachments enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_items enable row level security;
alter table public.team_votes enable row level security;
alter table public.audit_logs enable row level security;
alter table public.registration_attempts enable row level security;

drop policy if exists users_select_self_or_admin on public.users;
create policy users_select_self_or_admin
on public.users
for select
to authenticated
using (auth_user_id = auth.uid() or private.watchlist_is_admin());

drop policy if exists entries_select_public_catalog on public.entries;
create policy entries_select_public_catalog
on public.entries
for select
to anon, authenticated
using (true);

drop policy if exists entries_admin_write on public.entries;
create policy entries_admin_write
on public.entries
for all
to authenticated
using (private.watchlist_is_admin())
with check (private.watchlist_is_admin());

drop policy if exists entry_reactions_select_public on public.entry_reactions;
create policy entry_reactions_select_public
on public.entry_reactions
for select
to anon, authenticated
using (true);

drop policy if exists entry_reactions_user_write on public.entry_reactions;
create policy entry_reactions_user_write
on public.entry_reactions
for all
to authenticated
using (user_id = private.watchlist_user_id())
with check (user_id = private.watchlist_user_id());

drop policy if exists friends_participant_select on public.friends;
create policy friends_participant_select
on public.friends
for select
to authenticated
using (user_id = private.watchlist_user_id() or friend_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists friends_participant_write on public.friends;
create policy friends_participant_write
on public.friends
for all
to authenticated
using (user_id = private.watchlist_user_id() or friend_id = private.watchlist_user_id() or private.watchlist_is_admin())
with check (user_id = private.watchlist_user_id() or friend_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists friend_messages_participant_select on public.friend_messages;
create policy friend_messages_participant_select
on public.friend_messages
for select
to authenticated
using (sender_id = private.watchlist_user_id() or receiver_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists friend_messages_participant_insert on public.friend_messages;
create policy friend_messages_participant_insert
on public.friend_messages
for insert
to authenticated
with check (sender_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists reports_owner_or_admin_select on public.reports;
create policy reports_owner_or_admin_select
on public.reports
for select
to authenticated
using (user_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists reports_user_insert on public.reports;
create policy reports_user_insert
on public.reports
for insert
to authenticated
with check (user_id = private.watchlist_user_id());

drop policy if exists reports_owner_or_admin_update on public.reports;
create policy reports_owner_or_admin_update
on public.reports
for update
to authenticated
using (user_id = private.watchlist_user_id() or private.watchlist_is_admin())
with check (user_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists report_messages_owner_or_admin_select on public.report_messages;
create policy report_messages_owner_or_admin_select
on public.report_messages
for select
to authenticated
using (
  private.watchlist_is_admin()
  or exists (
    select 1 from public.reports r
    where r.id = report_messages.report_id and r.user_id = private.watchlist_user_id()
  )
);

drop policy if exists report_messages_owner_or_admin_insert on public.report_messages;
create policy report_messages_owner_or_admin_insert
on public.report_messages
for insert
to authenticated
with check (
  private.watchlist_is_admin()
  or exists (
    select 1 from public.reports r
    where r.id = report_messages.report_id and r.user_id = private.watchlist_user_id()
  )
);

drop policy if exists report_attachments_owner_or_admin_select on public.report_attachments;
create policy report_attachments_owner_or_admin_select
on public.report_attachments
for select
to authenticated
using (
  private.watchlist_is_admin()
  or exists (
    select 1 from public.reports r
    where r.id = report_attachments.report_id and r.user_id = private.watchlist_user_id()
  )
);

drop policy if exists report_attachments_owner_or_admin_insert on public.report_attachments;
create policy report_attachments_owner_or_admin_insert
on public.report_attachments
for insert
to authenticated
with check (user_id = private.watchlist_user_id() or private.watchlist_is_admin());

drop policy if exists teams_member_select on public.teams;
create policy teams_member_select
on public.teams
for select
to authenticated
using (
  owner_id = private.watchlist_user_id()
  or private.watchlist_is_admin()
  or exists (
    select 1 from public.team_members tm
    where tm.team_id = teams.id and tm.user_id = private.watchlist_user_id()
  )
);

drop policy if exists team_members_member_select on public.team_members;
create policy team_members_member_select
on public.team_members
for select
to authenticated
using (
  user_id = private.watchlist_user_id()
  or private.watchlist_is_admin()
  or exists (
    select 1 from public.teams t
    where t.id = team_members.team_id and t.owner_id = private.watchlist_user_id()
  )
);

drop policy if exists team_items_member_select on public.team_items;
create policy team_items_member_select
on public.team_items
for select
to authenticated
using (
  private.watchlist_is_admin()
  or exists (
    select 1 from public.team_members tm
    where tm.team_id = team_items.team_id and tm.user_id = private.watchlist_user_id()
  )
);

drop policy if exists team_votes_member_select on public.team_votes;
create policy team_votes_member_select
on public.team_votes
for select
to authenticated
using (user_id = private.watchlist_user_id() or private.watchlist_is_admin());

create or replace function private.watchlist_broadcast(topic text, event_name text, payload jsonb)
returns void
language plpgsql
security definer
set search_path = public, realtime
as $$
begin
  perform realtime.send(payload, event_name, topic, false);
exception
  when undefined_function or undefined_table or insufficient_privilege then
    null;
end;
$$;

create or replace function private.watchlist_friend_message_broadcast()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform private.watchlist_broadcast(
    'watchlist:user:' || new.sender_id::text,
    'friend_message',
    jsonb_build_object('relationId', new.relation_id, 'messageId', new.id)
  );
  perform private.watchlist_broadcast(
    'watchlist:user:' || new.receiver_id::text,
    'friend_message',
    jsonb_build_object('relationId', new.relation_id, 'messageId', new.id)
  );
  return new;
end;
$$;

drop trigger if exists watchlist_friend_message_broadcast on public.friend_messages;
create trigger watchlist_friend_message_broadcast
after insert on public.friend_messages
for each row execute function private.watchlist_friend_message_broadcast();

create or replace function private.watchlist_friend_relation_broadcast()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id integer;
  target_friend_id integer;
  relation_id integer;
begin
  target_user_id := coalesce(new.user_id, old.user_id);
  target_friend_id := coalesce(new.friend_id, old.friend_id);
  relation_id := coalesce(new.id, old.id);
  perform private.watchlist_broadcast('watchlist:user:' || target_user_id::text, 'friend_relation', jsonb_build_object('relationId', relation_id));
  perform private.watchlist_broadcast('watchlist:user:' || target_friend_id::text, 'friend_relation', jsonb_build_object('relationId', relation_id));
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists watchlist_friend_relation_broadcast on public.friends;
create trigger watchlist_friend_relation_broadcast
after insert or update or delete on public.friends
for each row execute function private.watchlist_friend_relation_broadcast();

create or replace function private.watchlist_report_message_broadcast()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id integer;
begin
  select user_id into owner_id from public.reports where id = new.report_id;
  if owner_id is not null then
    perform private.watchlist_broadcast(
      'watchlist:user:' || owner_id::text,
      'report_message',
      jsonb_build_object('reportId', new.report_id, 'messageId', new.id)
    );
  end if;
  perform private.watchlist_broadcast('watchlist:admin', 'report_message', jsonb_build_object('reportId', new.report_id, 'messageId', new.id));
  return new;
end;
$$;

drop trigger if exists watchlist_report_message_broadcast on public.report_messages;
create trigger watchlist_report_message_broadcast
after insert on public.report_messages
for each row execute function private.watchlist_report_message_broadcast();

create or replace function private.watchlist_maintenance_cleanup()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer := 0;
  changed integer := 0;
begin
  delete from public.registration_attempts where created_at < now() - interval '30 days';
  get diagnostics changed = row_count;
  affected := affected + changed;

  delete from public.audit_logs where created_at < now() - interval '180 days';
  get diagnostics changed = row_count;
  affected := affected + changed;

  delete from public.friend_messages m
  where not exists (select 1 from public.friends f where f.id = m.relation_id)
     or not exists (select 1 from public.users u where u.id = m.sender_id)
     or not exists (select 1 from public.users u where u.id = m.receiver_id);
  get diagnostics changed = row_count;
  affected := affected + changed;

  update public.report_messages rm
  set sender_id = null
  where rm.sender_id is not null
    and not exists (select 1 from public.users u where u.id = rm.sender_id);
  get diagnostics changed = row_count;
  affected := affected + changed;

  return affected;
end;
$$;

do $$
begin
  create extension if not exists pg_cron with schema extensions;
exception
  when others then
    null;
end $$;

do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'cron') then
    if exists (select 1 from cron.job where jobname = 'watchlist-nightly-maintenance') then
      perform cron.unschedule('watchlist-nightly-maintenance');
    end if;
    perform cron.schedule(
      'watchlist-nightly-maintenance',
      '15 3 * * *',
      $job$select private.watchlist_maintenance_cleanup();$job$
    );
  end if;
exception
  when others then
    null;
end $$;
